#!/usr/bin/env python3
"""Bake the logo map into the widget JSX.

Übersicht re-runs `command` every refresh and pipes stdout into render().
Shipping 40KB of base64 through that path each time is wasteful and appears
to exceed what the widget reliably receives — the widget went blank. The
logos never change between refreshes, so they belong in the widget source,
loaded once, while the command output stays ~1.5KB.
"""
import json, pathlib, re

root = pathlib.Path("/Users/anujpatel/projects/aiquota")
logos = json.load(open(root / "aiquota/assets/logos.json"))
jsx = root / "widgets/ubersicht/aiquota.jsx"
s = jsx.read_text()
# 1. command: drop --logos, back to the small payload
s = s.replace("aiquota --json --logos --ttl 240", "aiquota --json --ttl 240")

# 2. inject (or replace) the baked-in logo map
block = "const LOGOS = " + json.dumps(logos, separators=(",", ":")) + ";\n"
marker = "// --- BAKED LOGOS (generated by scripts/bake_logos.py) ---\n"
start = s.find(marker)
if start != -1:
    end = s.find("\n", s.find("const LOGOS =", start)) + 1
    s = s[:start] + marker + block + s[end:]
else:
    anchor = "export const command ="
    s = s.replace(anchor, marker + block + "\n" + anchor, 1)

# 3. render from the baked map instead of the per-service field
s = s.replace("{s.logo ? (", "{LOGOS[s.name] ? (")
s = s.replace('<img className="logo" src={s.logo} alt="" />',
              '<img className="logo" src={LOGOS[s.name]} alt="" />')

jsx.write_text(s)

# Ship the BUILT widget inside the package. Without this the wheel would
# carry a stale copy (or none), and `aiquota install-widget` would place a
# widget that doesn't match the repo.
import shutil
pkg = root / "aiquota/widgets"
pkg.mkdir(exist_ok=True)
shutil.copyfile(jsx, pkg / "aiquota.jsx")
for f in ("aiquota.5m.sh", "aiquota_render.py", "add_account.sh"):
    shutil.copyfile(root / "widgets/swiftbar" / f, pkg / f)

print(f"baked {len(logos)} logos into the widget ({round(len(block)/1024)} KB)")
print(f"synced 4 widget files into {pkg.relative_to(root)}/")
